--
-- posts
--
create table posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) not null,
  body text not null,
  location geometry(point, 4326) not null,
  created_at timestamp with time zone default current_timestamp not null
);

--
-- votes
--
create table votes (
  user_id uuid references auth.users (id) not null,
  post_id bigint references posts (id) not null,
  vote smallint not null,
  created_at timestamp with time zone default current_timestamp not null,
  updated_at timestamp with time zone default current_timestamp not null,
  primary key (user_id, post_id)
);

--
-- comments
--
create table comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) not null,
  post_id bigint references posts (id) not null,
  body text not null,
  created_at timestamp with time zone default current_timestamp not null
);

--
-- conversations
--
create table conversations (
  id bigint generated by default as identity primary key,
  target_type conversation_target_type not null,
  target_id bigint not null,
  one_id uuid references auth.users (id) not null,
  two_id uuid references auth.users (id) not null,
  one_last_seen timestamp with time zone,
  two_last_seen timestamp with time zone,
  created_at timestamp with time zone default current_timestamp not null,
  updated_at timestamp with time zone default current_timestamp not null
);

--
-- messages
--
create table messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references conversations (id) not null,
  user_id uuid references auth.users (id) not null,
  body text not null,
  attachment jsonb,
  created_at timestamp with time zone default current_timestamp not null
);

